### ISSUE TITLE
Screen Shot - Video 

### ISSUE THREAD

**Issue by abigdreamer** [gnufied/custom_toolbar#1]
Can you upload a screen shot of what this looks like? Any short video on youtube?

**Comment by gnufied** [comment]
This is how it looks right now.
![rbkit-new](https://cloud.githubusercontent.com/assets/278/8294054/9bf5da5a-1907-11e5-94f6-930a59291596.png)

The latest code is here though, https://github.com/code-mancers/rbkit-client
